import Foundation

/// Exercise name -> `Assets.xcassets/ExercisePhotos` imageset name. Sourced from
/// wger.de's open exercise database (CC-BY-SA), downloaded and converted to PNG by
/// `WgerCatalogMigration`'s companion import script. Not every wger exercise has a
/// photo — a missing entry here just means that exercise falls back to its SF Symbol.
enum ExerciseImageMapping {
    static let assetName: [String: String] = [
        "Ab wheel": "ab_wheel",
        "Active Hip Flexor to Hamstring Stretch": "active_hip_flexor_to_hamstring_stretch",
        "Arnold Shoulder Press": "arnold_shoulder_press",
        "B-Stance Reciprocal Single-Arm Row": "b_stance_reciprocal_single_arm_row",
        "Banana Kicks": "banana_kicks",
        "Banded Cat-Cow": "banded_cat_cow",
        "Banded Eccentric Single-Leg Slider Hamstring Curl": "banded_eccentric_single_leg_slider_hamstring_curl",
        "Barbell Hip Thrust": "barbell_hip_thrust",
        "90° Rotational Lunge to Box Step-Up": "90_rotational_lunge_to_box_step_up",
        "Alternating Biceps Curls With Dumbbell": "alternating_biceps_curls_with_dumbbell",
        "Alternating bicep curls": "alternating_bicep_curls",
        "Alternating dumbbell hammer curl": "alternating_dumbbell_hammer_curl",
        "Ankle Roll": "ankle_roll",
        "Arabesque": "arabesque",
        "Axe Hold": "axe_hold",
        "Back extensión": "back_extensi_n",
        "Band Terminal Knee extension": "band_terminal_knee_extension",
        "Banded Ankle Mobility": "banded_ankle_mobility",
        "Barbell Ab Rollout": "barbell_ab_rollout",
        "Barbell Clean and press": "barbell_clean_and_press",
        "Barbell Full Squat": "barbell_full_squat",
        "Barbell Step Back Lunge": "barbell_step_back_lunge",
        "Barbell Triceps Extension": "barbell_triceps_extension",
        "Barbell Wrist Curl": "barbell_wrist_curl",
        "Bench Press": "bench_press",
        "Bench Press Narrow Grip": "bench_press_narrow_grip",
        "Benchpress Dumbbells": "benchpress_dumbbells",
        "Bent High Pulls": "bent_high_pulls",
        "Bent Over Dumbbell Rows": "bent_over_dumbbell_rows",
        "Bent Over Rowing": "bent_over_rowing",
        "Bent Over Rowing Reverse": "bent_over_rowing_reverse",
        "Biceps Curl With Cable": "biceps_curl_with_cable",
        "Biceps Curls With Barbell": "biceps_curls_with_barbell",
        "Biceps Curls With Dumbbell": "biceps_curls_with_dumbbell",
        "Biceps Curls With SZ-bar": "biceps_curls_with_sz_bar",
        "Biceps with TRX": "biceps_with_trx",
        "Bird Dog": "bird_dog",
        "Blackroll": "blackroll",
        "Box squat": "box_squat",
        "Bulgarian Squat with Dumbbells": "bulgarian_squat_with_dumbbells",
        "Bulgarian split squats left": "bulgarian_split_squats_left",
        "Bus Drivers": "bus_drivers",
        "Butterfly": "butterfly",
        "Cable Concentration Curl": "cable_concentration_curl",
        "Cable Cross-over": "cable_cross_over",
        "Cable Front Raise with a small bar": "cable_front_raise_with_a_small_bar",
        "Cable Lateral Raises (Single Arm)": "cable_lateral_raises_single_arm",
        "Cable Rear Delt Fly": "cable_rear_delt_fly",
        "Cable glute extension": "cable_glute_extension",
        "Calf Press Using Leg Press Machine": "calf_press_using_leg_press_machine",
        "Calves foam roller": "calves_foam_roller",
        "Chest Press": "chest_press",
        "Child's pose": "child_s_pose",
        "Chin Up": "chin_up",
        "Clap Push-UP": "clap_push_up",
        "Claps over the head": "claps_over_the_head",
        "Clean and Press": "clean_and_press",
        "Close-grip Lat Pull Down": "close_grip_lat_pull_down",
        "Close-grip Press-ups": "close_grip_press_ups",
        "Close-grip supinated lat pulldown": "close_grip_supinated_lat_pulldown",
        "Cross-Bench Dumbbell Pullovers": "cross_bench_dumbbell_pullovers",
        "Crunches": "crunches",
        "Curl De Muñeca Con Barra": "curl_de_mu_eca_con_barra",
        "Deadlifts": "deadlifts",
        "Decline Bench Leg Raise": "decline_bench_leg_raise",
        "Decline Bench Press Barbell": "decline_bench_press_barbell",
        "Devil’s Press": "devil_s_press",
        "Dips": "dips",
        "Dips Between Two Benches": "dips_between_two_benches",
        "Double Leg Calf Raise": "double_leg_calf_raise",
        "Dumbbell Bent Over Face Pull": "dumbbell_bent_over_face_pull",
        "Dumbbell Floor Press": "dumbbell_floor_press",
        "Dumbbell Front Squat": "dumbbell_front_squat",
        "Dumbbell Goblet Squat": "dumbbell_goblet_squat",
        "Dumbbell Hang Power Cleans": "dumbbell_hang_power_cleans",
        "Dumbbell Hex Press": "dumbbell_hex_press",
        "Dumbbell Hip Thrust": "dumbbell_hip_thrust",
        "Dumbbell Lunges Walking": "dumbbell_lunges_walking",
        "Dumbbell Rear Lunge": "dumbbell_rear_lunge",
        "Dumbbell Romanian Deadlift": "dumbbell_romanian_deadlift",
        "Dumbbell Side Bend": "dumbbell_side_bend",
        "Dumbbell Side Squat": "dumbbell_side_squat",
        "Dumbbell bicep curl to press": "dumbbell_bicep_curl_to_press",
        "Dumbbell donkey kick": "dumbbell_donkey_kick",
        "Dumbbell rear delt row": "dumbbell_rear_delt_row",
        "Dumbbell sumo deadlift": "dumbbell_sumo_deadlift",
        "Dumbbell wide bicep curls": "dumbbell_wide_bicep_curls",
        "External Rotation Stretch": "external_rotation_stretch",
        "Face pulls with yellow/green band": "face_pulls_with_yellow_green_band",
        "Finger Pushup": "finger_pushup",
        "Floor dips": "floor_dips",
        "Fly With Cable": "fly_with_cable",
        "Fly With Dumbbells": "fly_with_dumbbells",
        "Foam Roller Adductors": "foam_roller_adductors",
        "Foam Roller Anterior tibialis": "foam_roller_anterior_tibialis",
        "Foam Roller Gluteus": "foam_roller_gluteus",
        "Foam Roller Iliotibial band": "foam_roller_iliotibial_band",
        "Foam Roller quadriceps": "foam_roller_quadriceps",
        "Forearm Curls (underhand grip)": "forearm_curls_underhand_grip",
        "Front Raises": "front_raises",
        "Front Squats": "front_squats",
        "Good Morning": "good_morning",
        "Hammer Curls": "hammer_curls",
        "Hammercurls on Cable": "hammercurls_on_cable",
        "Hammerstrength Decline Chest Press": "hammerstrength_decline_chest_press",
        "Hamstring Foam roller": "hamstring_foam_roller",
        "Hamstring Kicks": "hamstring_kicks",
        "Hand Grip": "hand_grip",
        "Handstand Pushup": "handstand_pushup",
        "Head tilts": "head_tilts",
        "Head turns": "head_turns",
        "High Knee Jumps": "high_knee_jumps",
        "High knees": "high_knees",
        "High-Cable Cross Tricep Extention - NB": "high_cable_cross_tricep_extention_nb",
        "High-pulley pullover": "high_pulley_pullover",
        "Hindu Pushups": "hindu_pushups",
        "Hip Circles": "hip_circles",
        "Hip Crossover": "hip_crossover",
        "Hip Flexor Stretch": "hip_flexor_stretch",
        "Hollow Hold": "hollow_hold",
        "Hyperextensions": "hyperextensions",
        "Incline Bench Press - Barbell": "incline_bench_press_barbell",
        "Incline Bench Press - Dumbbell": "incline_bench_press_dumbbell",
        "Incline Bench Press - MP": "incline_bench_press_mp",
        "Incline Bench Reverse Fly": "incline_bench_reverse_fly",
        "Incline Chest-Supported Dumbbell Row": "incline_chest_supported_dumbbell_row",
        "Incline Crunches": "incline_crunches",
        "Incline bench pulldown": "incline_bench_pulldown",
        "Inverted Rows": "inverted_rows",
        "Isometric Squat to Failure": "isometric_squat_to_failure",
        "Jumping Jacks": "jumping_jacks",
        "Kettlebell One Legged Deadlift": "kettlebell_one_legged_deadlift",
        "Kettlebell Swing": "kettlebell_swing",
        "Kettlebell deadlifts": "kettlebell_deadlifts",
        "Knee Raises": "knee_raises",
        "Knee to Chest Stretch": "knee_to_chest_stretch",
        "Kneeling kickbacks": "kneeling_kickbacks",
        "Lateral Push Off": "lateral_push_off",
        "Lateral Raises": "lateral_raises",
        "Lateral Rows on Cable, One Armed": "lateral_rows_on_cable_one_armed",
        "Leg Curl": "leg_curl",
        "Leg Curls (laying)": "leg_curls_laying",
        "Leg Curls (sitting)": "leg_curls_sitting",
        "Leg Curls (standing)": "leg_curls_standing",
        "Leg Extension": "leg_extension",
        "Leg Press": "leg_press",
        "Leg Press on Hackenschmidt Machine": "leg_press_on_hackenschmidt_machine",
        "Leg Presses (narrow)": "leg_presses_narrow",
        "Leg Raises, Lying": "leg_raises_lying",
        "Leg raises pull up bar": "leg_raises_pull_up_bar",
        "Long-Pulley (low Row)": "long_pulley_low_row",
        "Low-Cable Cross-Over - NB": "low_cable_cross_over_nb",
        "Lower Back Extensions": "lower_back_extensions",
        "Lunge with Twist Stretch": "lunge_with_twist_stretch",
        "Lunges": "lunges",
        "Lying Figure Four Stretch": "lying_figure_four_stretch",
        "Lying Hamstring Stretch with Band": "lying_hamstring_stretch_with_band",
        "Machine Hip Abduction": "machine_hip_abduction",
        "Machine Lateral Raise": "machine_lateral_raise",
        "Machine Leg Flexion": "machine_leg_flexion",
        "Machine Side Lateral Raises": "machine_side_lateral_raises",
        "Machine chest fly": "machine_chest_fly",
        "Marching High Knees": "marching_high_knees",
        "Medicine ball booklet crunch": "medicine_ball_booklet_crunch",
        "Medicine ball twist": "medicine_ball_twist",
        "Mentzer Pulldown": "mentzer_pulldown",
        "Military Press mit SZ-Bar": "military_press_mit_sz_bar",
        "Modified pulldown": "modified_pulldown",
        "Negative Crunches": "negative_crunches",
        "Neutral-grip chest pulldown": "neutral_grip_chest_pulldown",
        "Neutral-grip pull-ups or TRX rows": "neutral_grip_pull_ups_or_trx_rows",
        "One Arm Bent Row": "one_arm_bent_row",
        "Overhead Barbell Press": "overhead_barbell_press",
        "Overhead Triceps Extension": "overhead_triceps_extension",
        "Pallof Press": "pallof_press",
        "Pendular hack": "pendular_hack",
        "Pigeon Stretch": "pigeon_stretch",
        "Pike Push Ups": "pike_push_ups",
        "Pistol Squat": "pistol_squat",
        "Plank": "plank",
        "Plank Shoulder Taps": "plank_shoulder_taps",
        "Plantarflexion Stretch with Band": "plantarflexion_stretch_with_band",
        "Preacher Curls": "preacher_curls",
        "Pull-ups": "pull_ups",
        "Push Press": "push_press",
        "Push-Up": "push_up",
        "Push-Ups | Decline": "push_ups_decline",
        "Quad Stretch": "quad_stretch",
        "Quadriped Arm and Leg Raise": "quadriped_arm_and_leg_raise",
        "Rack Deadlift": "rack_deadlift",
        "Rear Delt Raises": "rear_delt_raises",
        "Remo maquina agarre estrecho": "remo_maquina_agarre_estrecho",
        "Remo maquina agarre estrecho supino": "remo_maquina_agarre_estrecho_supino",
        "Reverse Grip Barbell Curls": "reverse_grip_barbell_curls",
        "Reverse Nordic Curl": "reverse_nordic_curl",
        "Reverse lunges": "reverse_lunges",
        "Rope Pullover/row": "rope_pullover_row",
        "Rowing seated, narrow grip": "rowing_seated_narrow_grip",
        "Rowing, T-bar": "rowing_t_bar",
        "Runners Lunge Stretch": "runners_lunge_stretch",
        "Russian Twist": "russian_twist",
        "Seated Cable Row": "seated_cable_row",
        "Seated Cable chest fly": "seated_cable_chest_fly",
        "Seated Dumbbell Calf Raise": "seated_dumbbell_calf_raise",
        "Seated Hip Adduction": "seated_hip_adduction",
        "Seated Knee Tuck": "seated_knee_tuck",
        "Seated Row (Machine)": "seated_row_machine",
        "Seated W Curl": "seated_w_curl",
        "Seated rear delt rise": "seated_rear_delt_rise",
        "Shoulder Press, Barbell": "shoulder_press_barbell",
        "Shoulder Press, Dumbbells": "shoulder_press_dumbbells",
        "Shoulder Press, on Machine": "shoulder_press_on_machine",
        "Shoulder Raise (Dumbbell)": "shoulder_raise_dumbbell",
        "Shoulder Shrug": "shoulder_shrug",
        "Shrugs, Barbells": "shrugs_barbells",
        "Shrugs, Dumbbells": "shrugs_dumbbells",
        "Side Crunch": "side_crunch",
        "Side bend": "side_bend",
        "Side stretch": "side_stretch",
        "Side-laying interior rotation": "side_laying_interior_rotation",
        "Single Arm Plank to Row": "single_arm_plank_to_row",
        "Single arm row": "single_arm_row",
        "Single-Leg Deadlift with Dumbbell": "single_leg_deadlift_with_dumbbell",
        "Single-Leg Lunge with Kettlebell:": "single_leg_lunge_with_kettlebell",
        "Single-arm dumbbell shoulder press": "single_arm_dumbbell_shoulder_press",
        "Single-leg side glute press": "single_leg_side_glute_press",
        "Sit Up Elbow Thrust": "sit_up_elbow_thrust",
        "Sitting Calf Stretch (Dorsiflexion)": "sitting_calf_stretch_dorsiflexion",
        "Skullcrusher SZ-bar": "skullcrusher_sz_bar",
        "Sliding Lateral Lunge": "sliding_lateral_lunge",
        "Sloper hanging": "sloper_hanging",
        "Slow Squat": "slow_squat",
        "Smith Machine Slight Incline Press": "smith_machine_slight_incline_press",
        "Smith Machine Split Squat": "smith_machine_split_squat",
        "Smith Press": "smith_press",
        "Smith machine squat": "smith_machine_squat",
        "Standing Calf Raises": "standing_calf_raises",
        "Standing Calf Stretch": "standing_calf_stretch",
        "Standing IT Band Stretch": "standing_it_band_stretch",
        "Standing biceps stretch left": "standing_biceps_stretch_left",
        "Standing biceps stretch right": "standing_biceps_stretch_right",
        "Stationary bike cardio": "stationary_bike_cardio",
        "Step Jack": "step_jack",
        "Step-ups": "step_ups",
        "Straight Bar Cable Curls": "straight_bar_cable_curls",
        "Straight-Arm Pulldown (Cable)": "straight_arm_pulldown_cable",
        "Sumo Deadlift": "sumo_deadlift",
        "Supported Calf Stretch": "supported_calf_stretch",
        "Suspended crossess": "suspended_crossess",
        "TRX Rows": "trx_rows",
        "Talons fesses": "talons_fesses",
        "Torso Twist": "torso_twist",
        "Trap press": "trap_press",
        "Treadmill Cardio": "treadmill_cardio",
        "Tricep Pushdown on Cable": "tricep_pushdown_on_cable",
        "Tricep Rope Pushdowns": "tricep_rope_pushdowns",
        "Triceps Extensions on Cable": "triceps_extensions_on_cable",
        "Triceps Overhead (Dumbbell)": "triceps_overhead_dumbbell",
        "Triceps Pushdown": "triceps_pushdown",
        "Triceps stretch left": "triceps_stretch_left",
        "Triceps stretch right": "triceps_stretch_right",
        "Tuck planche": "tuck_planche",
        "Unilateral Cable row": "unilateral_cable_row",
        "Upright Row w/ Dumbbells": "upright_row_w_dumbbells",
        "Upright Row, SZ-bar": "upright_row_sz_bar",
        "Upright Row, on Multi Press": "upright_row_on_multi_press",
        "Wall balls": "wall_balls",
        "Weighted Crunch": "weighted_crunch",
        "Weighted push-ups": "weighted_push_ups",
        "ankle dorsiflexion rocks": "ankle_dorsiflexion_rocks",
        "dumbbell snatch": "dumbbell_snatch",
        "kettlebell sumo deadlift": "kettlebell_sumo_deadlift",
        "one-handed kettlebell curls": "one_handed_kettlebell_curls",
        "rubber band glute kickback": "rubber_band_glute_kickback",
    ]
}
