import Foundation

/// Exercise name -> `Assets.xcassets/ExercisePhotos` imageset name, for the subset
/// of the catalog matched (by name, at authoring time) against free-exercise-db
/// (public domain / Unlicense). Not every exercise has a match; lookups for names
/// not in this table simply mean no photo, fall back to the SF Symbol icon.
enum ExerciseImageMapping {
    static let assetName: [String: String] = [
        "Ankle Circles": "Ankle_Circles",
        "Arm Circles": "Arm_Circles",
        "Arnold Press": "Arnold_Dumbbell_Press",
        "Band Pull-Apart": "Band_Pull_Apart",
        "Barbell Back Squat": "Barbell_Squat",
        "Barbell Bench Press": "Barbell_Bench_Press_-_Medium_Grip",
        "Barbell Curl": "Barbell_Curl",
        "Barbell Deadlift": "Barbell_Deadlift",
        "Barbell Front Squat": "Front_Barbell_Squat",
        "Barbell Good Morning": "Good_Morning",
        "Barbell Hip Thrust": "Barbell_Hip_Thrust",
        "Barbell Lunge": "Barbell_Lunge",
        "Barbell Overhead Press": "Barbell_Shoulder_Press",
        "Barbell Row": "Bent_Over_Barbell_Row",
        "Barbell Shrug": "Barbell_Shrug",
        "Barbell Sumo Squat": "Barbell_Squat",
        "Bench Dips": "Bench_Dips",
        "Bodyweight Lunge": "Bodyweight_Walking_Lunge",
        "Bodyweight Squat": "Bodyweight_Squat",
        "Box Jump": "Box_Jump_Multiple_Response",
        "Cable Crunch": "Cable_Crunch",
        "Cable Face Pull": "Face_Pull",
        "Cable Lateral Raise": "Cable_Seated_Lateral_Raise",
        "Cable Tricep Pushdown": "Triceps_Pushdown",
        "Calf Raise": "Calf_Raises_-_With_Bands",
        "Cat-Cow Stretch": "Cat_Stretch",
        "Chest Dip": "Dips_-_Chest_Version",
        "Chin-Up": "Chin-Up",
        "Close-Grip Flat Dumbbell Press": "Close-Grip_Dumbbell_Press",
        "Dead Bug": "Dead_Bug",
        "Decline Barbell Bench Press": "Decline_Barbell_Bench_Press",
        "Decline Dumbbell Fly (-30°)": "Decline_Dumbbell_Flyes",
        "Decline Dumbbell Press (-30°)": "Decline_Dumbbell_Bench_Press",
        "Depth Jump": "Depth_Jump_Leap",
        "Diamond Push-Up": "Pushups",
        "Dumbbell Bench Press": "Dumbbell_Bench_Press",
        "Dumbbell Bulgarian Split Squat": "Split_Squat_with_Dumbbells",
        "Dumbbell Concentration Curl": "Concentration_Curls",
        "Dumbbell Curl": "Dumbbell_Bicep_Curl",
        "Dumbbell Front Raise": "Front_Dumbbell_Raise",
        "Dumbbell Goblet Squat": "Dumbbell_Squat",
        "Dumbbell Lateral Raise": "Dumbbell_Raise",
        "Dumbbell Lunge": "Dumbbell_Lunges",
        "Dumbbell Overhead Triceps Extension": "Sled_Overhead_Triceps_Extension",
        "Dumbbell Preacher Curl": "One_Arm_Dumbbell_Preacher_Curl",
        "Dumbbell Rear Delt Fly": "Cable_Rear_Delt_Fly",
        "Dumbbell Rolling Shrug (Backward Rotation)": "Dumbbell_Shrug",
        "Dumbbell Rolling Shrug (Forward Rotation)": "Dumbbell_Shrug",
        "Dumbbell Romanian Deadlift": "Romanian_Deadlift",
        "Dumbbell Row": "One-Arm_Dumbbell_Row",
        "Dumbbell Shoulder Press": "Dumbbell_Shoulder_Press",
        "Dumbbell Shrug": "Dumbbell_Shrug",
        "Dumbbell Skull Crusher (Hammer Grip)": "EZ-Bar_Skullcrusher",
        "Dumbbell Step-Up": "Dumbbell_Step_Ups",
        "EZ Bar Curl": "EZ-Bar_Curl",
        "EZ Bar Preacher Curl": "EZ-Bar_Curl",
        "EZ Bar Skull Crusher": "EZ-Bar_Skullcrusher",
        "External Rotation": "External_Rotation",
        "Face Pull with Band": "Face_Pull",
        "Glute Bridge": "Barbell_Glute_Bridge",
        "Hammer Curl": "Hammer_Curls",
        "Handstand Push-Up": "Handstand_Push-Ups",
        "Hanging Around the World": "Around_The_Worlds",
        "Hanging Leg Raise": "Hanging_Leg_Raise",
        "Hanging Straight Leg Raise": "Hanging_Leg_Raise",
        "Hip Circles": "Hip_Circles_prone",
        "Inchworm": "Inchworm",
        "Incline Barbell Bench Press": "Barbell_Incline_Bench_Press_-_Medium_Grip",
        "Incline Dumbbell Curl (45°)": "Incline_Dumbbell_Curl",
        "Incline Dumbbell Fly (45°)": "Incline_Dumbbell_Flyes",
        "Incline Dumbbell Press": "Incline_Dumbbell_Press",
        "Incline Lying Triceps Extension": "Incline_Barbell_Triceps_Extension",
        "Internal Rotation": "Internal_Rotation_with_Band",
        "Inverted Row": "Inverted_Row",
        "Jump Squat": "Freehand_Jump_Squat",
        "Kettlebell Clean and Press": "Clean_and_Press",
        "Kettlebell Goblet Squat": "Goblet_Squat",
        "Kettlebell Swing": "One-Arm_Kettlebell_Swings",
        "Kettlebell Turkish Get-Up": "Kettlebell_Turkish_Get-Up_Lunge_style",
        "Lat Pulldown": "Wide-Grip_Lat_Pulldown",
        "Leg Curl": "Ball_Leg_Curl",
        "Leg Extension": "Leg_Extensions",
        "Leg Press": "Leg_Press",
        "Leg Raise": "Rear_Leg_Raises",
        "Lying Dumbbell Triceps Extension (Cross-Face)": "Lying_Dumbbell_Tricep_Extension",
        "Medicine Ball Chest Pass": "Medicine_Ball_Chest_Pass",
        "Medicine Ball Slam": "One-Arm_Medicine_Ball_Slam",
        "Monster Walk": "Monster_Walk",
        "Mountain Climber": "Mountain_Climbers",
        "Muscle-Up": "Muscle_Up",
        "Neck Stretch": "Side_Neck_Stretch",
        "Pike Push-Up": "Pushups",
        "Pistol Squat": "Kettlebell_Pistol_Squat",
        "Plank": "Plank",
        "Plyo Push-Up": "Plyo_Push-up",
        "Pull-Up": "Pullups",
        "Push-Up": "Pushups",
        "Ring Chin-Up": "Chin-Up",
        "Ring Pull-Up": "Pullups",
        "Romanian Deadlift": "Romanian_Deadlift",
        "Russian Twist": "Russian_Twist",
        "Seated Cable Row": "Seated_Cable_Rows",
        "Seated Calf Raise": "Seated_Calf_Raise",
        "Seated Dumbbell Shoulder Press (Rotated Grip)": "Dumbbell_Shoulder_Press",
        "Seated EZ Bar Triceps Extension": "Decline_EZ_Bar_Triceps_Extension",
        "Seated Two-Hand Dumbbell Overhead Triceps Extension": "Overhead_Triceps",
        "Single-Arm Dumbbell Row (3-Point Stance)": "One-Arm_Dumbbell_Row",
        "Single-Leg Glute Bridge": "Single_Leg_Glute_Bridge",
        "Sit-Up": "Sit-Up",
        "Sled Push": "Sled_Push",
        "Smith Machine Bench Press": "Smith_Machine_Bench_Press",
        "Smith Machine Squat": "Smith_Machine_Squat",
        "Standing Calf Raise": "Standing_Calf_Raises",
        "Standing Dumbbell Curl": "Standing_Dumbbell_Reverse_Curl",
        "Sumo Deadlift": "Sumo_Deadlift",
        "Superman": "Superman",
        "Trap Bar Deadlift": "Trap_Bar_Deadlift",
        "Tricep Dip": "Dips_-_Triceps_Version",
        "Triceps Kickback (3-Point Stance)": "Tricep_Dumbbell_Kickback",
        "Tuck Jump": "Knee_Tuck_Jump",
        "Walking Lunge": "Barbell_Walking_Lunge",
        "Wide Push-Up": "Push-Up_Wide",
        "World's Greatest Stretch": "Worlds_Greatest_Stretch",
        "Wrist Circles": "Wrist_Circles",
    ]
}
